adding logic for linting

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -101,6 +101,13 @@ jobs:
           command: |
             cd nginx_app          
             make lint
+            RESULT=$?
+            if [ ${RESULT} -eq 0 ]; then
+              echo "successfully linted dockerfile - proceeding to build image"
+            else
+              echo "failed to lint dockerfile - please fix and try again"
+            fi
+
 #   deploy-application:
 #     executor: aws-eks/python3
 #     steps:
