adding logic for linting

diff --git a/nginx_app/Makefile b/nginx_app/Makefile
--- a/nginx_app/Makefile
+++ b/nginx_app/Makefile
@@ -11,4 +11,12 @@ lint:
 	# See local hadolint install instructions:   https://github.com/hadolint/hadolint
 	# This is linter for Dockerfiles
 	./hadolint Dockerfile
+
+	RESULT=$?
+	if [ $RESULT -eq 0 ]; then
+		echo "successfully linted dockerfile - proceeding to build image"
+	else
+		echo "failed to lint dockerfile - please fix and try again"
+	fi
+
 all: install lint 
